# Generated by Django 5.2.12 on 2026-03-27 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('client', models.CharField(max_length=200, verbose_name='고객사')),
                ('description', models.TextField(blank=True, verbose_name='프로젝트 설명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('status', models.CharField(choices=[('waiting', '대기'), ('planning', ' 기획'), ('in_progress', '진행'), ('completed', '완료'), ('cancelled', '취소')], default='waiting', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='버전')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='예상원가')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='목표입찰가')),
                ('target_profit_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='목표수익률(%)')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='제안입찰가')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project')),
            ],
            options={
                'verbose_name': '프로젝트 버전',
                'verbose_name_plural': '프로젝트 버전들',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version_number')},
            },
        ),
    ]
