# Generated by Django 5.2.12 on 2026-03-27 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('budget_overrun', '예산 초과'), ('schedule_delay', '일정 지연'), ('resource_conflict', '인력 충돌'), ('approval_pending', '결재 대기'), ('milestone_approaching', '마일스톤 임박')], max_length=30)),
                ('level', models.CharField(choices=[('info', '정보'), ('warning', '경고'), ('critical', '심각')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='연결 링크')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_health', models.CharField(choices=[('healthy', '정상'), ('warning', '주의'), ('critical', '위험')], default='healthy', max_length=20)),
                ('schedule_health', models.CharField(choices=[('healthy', '정상'), ('warning', '주의'), ('critical', '위험')], default='healthy', max_length=20)),
                ('resource_health', models.CharField(choices=[('healthy', '정상'), ('warning', '주의'), ('critical', '위험')], default='healthy', max_length=20)),
                ('overall_health', models.CharField(choices=[('healthy', '정상'), ('warning', '주의'), ('critical', '위험')], default='healthy', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='projects.project')),
            ],
            options={
                'verbose_name': '프로젝트 상태',
                'verbose_name_plural': '프로젝트 상태들',
            },
        ),
    ]
