# Generated by Django 5.2.12 on 2026-03-27 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='작업명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='진행률(%)')),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '진행중'), ('completed', '완료'), ('delayed', '지연'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_milestone', models.BooleanField(default=False, verbose_name='마일스톤 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='schedule.task')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='schedule.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': '작업(WBS)',
                'verbose_name_plural': '작업들(WBS)',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('finish_to_start', '종료-시작 (FS)'), ('start_to_start', '시작-시작 (SS)'), ('finish_to_finish', '종료-종료 (FF)'), ('start_to_finish', '시작-종료 (SF)')], default='finish_to_start', max_length=20)),
                ('lag_days', models.IntegerField(default=0, verbose_name='지연 일수')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_relations', to='schedule.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_relations', to='schedule.task')),
            ],
            options={
                'verbose_name': '작업 의존성',
                'verbose_name_plural': '작업 의존성들',
            },
        ),
    ]
