# Generated by Django 5.2.12 on 2026-03-27 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='결재선명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 결재선')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '결재선',
                'verbose_name_plural': '결재선들',
            },
        ),
        migrations.CreateModel(
            name='ApprovalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='결재 유형')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('requires_expense', models.BooleanField(default=True, verbose_name='비용 연결 필요')),
            ],
            options={
                'verbose_name': '결재 유형',
                'verbose_name_plural': '결재 유형들',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='금액')),
                ('status', models.CharField(choices=[('draft', ' draft'), ('pending', '검토중'), ('approved', '승인'), ('rejected', '반려'), ('cancelled', '취소')], default='draft', max_length=20, verbose_name='상태')),
                ('current_step', models.IntegerField(default=0, verbose_name='현재 단계')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='projects.project')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('approval_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approvals.approvaltype', verbose_name='결재 유형')),
            ],
            options={
                'verbose_name': '결재',
                'verbose_name_plural': '결재들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '승인'), ('reject', '반려')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approval')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLineMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.approvalline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='approvalline',
            name='approvers',
            field=models.ManyToManyField(related_name='approval_lines', through='approvals.ApprovalLineMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='approvals.approval')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
