# Generated by Django 5.2.12 on 2026-03-27 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pm', 'PM'), ('designer', '설계담당'), ('constructor', '시공담당'), ('engineer', '엔지니어'), ('assistant', '보조')], max_length=20, verbose_name='역할')),
                ('start_date', models.DateField(verbose_name='투입 시작일')),
                ('end_date', models.DateField(verbose_name='투입 종료일')),
                ('allocation_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='투입률(%)')),
                ('hours_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='월稼働시간')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '인력 배치',
                'verbose_name_plural': '인력 배치들',
                'unique_together': {('project', 'user', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='ResourceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_allocation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflict_allocations', models.ManyToManyField(related_name='conflicts', to='resources.resourceallocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '인력 충돌',
                'verbose_name_plural': '인력 충돌들',
            },
        ),
    ]
