# Generated by Django 5.2.12 on 2026-03-29 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceallocation',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='cost.vendor'),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='hours_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='월 근무시간'),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
